# Docker Compose para Traefik 3.5 con buenas prácticas y monitoreo
# Author: Bismarck Villca <bismarck.villca@gmail.com>
name: traefik

services:
  traefik:
    network_mode: host
    extends:
      service: traefik
      file: services/traefik.yml
