# Traefik dynamic configuration
# This file enables configurations that reload automatically without restarting Traefik
# Author: Bismarck Villca <bismarck.villca@gmail.com>

http:
  middlewares:
    # Retry middleware to improve resilience
    retry:
      retry:
        attempts: 3
        initialInterval: "500ms"
