# Traefik 3.5 static configuration

log:
  level: INFO # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  # File provider for dynamic configuration
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true # Enable hot reloads

entryPoints:
  web:
    address: ":80"
  # Uncomment to enable HTTPS
  # websecure:
  #   address: ":443"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

metrics:
  prometheus:
    entryPoint: web
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
