# Configuración estática de Traefik 3.5

log:
  level: INFO # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO

api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  # Proveedor de archivos para configuración dinámica
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true # Habilita recargas automáticas en caliente

entryPoints:
  web:
    address: ":80"
  # Descomentar para habilitar HTTPS
  # websecure:
  #   address: ":443"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

metrics:
  prometheus:
    entryPoint: web
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
